### ISSUE TITLE
Underwater dashing through spikes with Water Thrusters in Marine Caves

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#161]
**Describe the bug**
There are actually no spikes on areas with water tiles, and breaking a tile that makes water flow out will wash all spikes away...

However, on Marine Caves tileset (Oceanic Caves in 2nd Campaign), the stage with changing tides of water, these spikes are around, even when they are submerged by the rising water.

Using Water Thrusters underwater only gets through enemies, but not through the spikes in Marine Caves... This makes the item description inconsistent with all other dashing items.

ArmsItem.tsc
```
#6042
<EQJ0042:7042<ELJ
<KEY<MSGMakes <NAM swim stronger,
and enables charged swims.<NOD
When underwater, empowers dashing,<NOD
allowing it to go through
enemies and spikes
without damage.<NOD<CLR
Do you want to equip it?<YNJ0000<EQ+0042<MSG
Equipped Water Thrusters.<NOD<WAI0003<FRE<EVE5042
```

**To Reproduce**
1. In a run, acquire Water Thrusters from a Chest.
2. Go to Marine Caves. May lock in with `"tileset":"Marine Caves"` in `config.json`.
3. Equip Water Thrusters and, while underwater, press [Dash] to try to go through spikes.
4. Player still gets hurt by the spikes...

**Version**
1.45.0.5 (And all versions prior)

**Comment by TrashboxBobylev** [comment]
This is actually a consequence of removing the ability to ignore lava by dashing, I believe.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.45.1.

**Comment by Fluff8836** [comment]
Unfortunately that did not fix the bug.

Water Thrusters underwater dashing through spikes in Marine Caves / Oceanic Caves, player still takes damage.

Version 1.45.1.2.

**Comment by TrashboxBobylev** [comment]
Fixed for real in 1.45.2.2.
