### ISSUE TITLE
Time Stop Ability can be used again even with cooldown

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#165]
**Describe the bug**
After time flows again, pressing [Ability] again during cooldown executes Time Stop again. This should not happen until after the cooldown finishes. This is a glitch. I will just attach a save file with the Shield of Time item already equipped.

[Profile.json](https://github.com/user-attachments/files/19924281/Profile.json) Shield of Time already equipped.

For items with Time Stop, that being Timeline Ring and the Miracle Crafted Shield of Time or Winter Clock.

**To Reproduce**
1. Place `Profile.json` to the folder where `Randamu.exe` is located, then open `Randamu.exe` and select Load from Save.
2. Press [Ability] to freeze time, and press [Ability] again just when cooldown has started.
3. **Unintended use during cooldown!**

**Version**
1.45.0.5

**Comment by TrashboxBobylev** [comment]
Fixed in 1.45.1.

**Comment by Fluff8836** [comment]
Unfortunately, that did not fix the bug. Pressing [Ability] with Timeline Ring equipped during 40 second cooldown **still executes Time Stop.**

Steps to reproduce the behavior:
1. Acquire Timeline Ring in a run, equip it.
2. Press [Ability] to freeze time, and press [Ability] again just after cooldown has started.
3. Unintended use during cooldown!

**Version**
1.45.1.2

**Comment by TrashboxBobylev** [comment]
Fixed for real in 1.45.2.2.
