### ISSUE TITLE
Movement of options from Gameplay to General broke the function

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#94]
"Moved some options from Gameplay section into General section."
That be Disable Music and Legacy Graphics. **Turning them on had no effect from the menu.** The only way is via config.json now.

1. Go to 'General Options' from the main menu
2. Turn on 'Disable Music' and/or 'Legacy Graphics'
3. Go back and then 'Start New Game'
4. Nothing changed. Open pause menu, select 'General Options'
5. Repeat step 2, go back and then 'Reset' and confirm.
6. Nothing changed.

Also, during the run, the option 'Disable Music' is still within 'Gameplay Options' through the pause menu and that still functions properly. Reset the game after toggling and the music does get disabled.

Version 1.44.0.0

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.1 (before the bug being reported here).

**Comment by DrippingYellow** [comment]
Not fixed. I booted up the latest 1.44.1 version and the Disable Music and Legacy Graphics settings are still not set properly in the general settings when I change them.

**Comment by TrashboxBobylev** [comment]
Yeah, I noticed... (don't want to make another revision tho......)

At least it properly saves now.

**Comment by TrashboxBobylev** [comment]
Fully fixed in 1.44.2.
